# Generated by Django 2.1.3 on 2019-03-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0004_remove_contract_zones")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("id",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        )
    ]
