# Generated by Django 2.2.8 on 2020-02-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0005_localize_verbose_names")]

    operations = [migrations.RemoveField(model_name="user", name="is_contractor")]
