# Generated by Django 2.1.3 on 2019-01-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("areas", "0001_initial"), ("events", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contract_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="areas.ContractZone",
                verbose_name="contract zone",
            ),
        )
    ]
