# Generated by Django 2.1.3 on 2019-02-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_additional_equipment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='areas.ContractZone', verbose_name='contract zone'),
        ),
    ]
