# Generated by Django 2.2.5 on 2019-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0005_add_small_trash_bag_remove_dumpster")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                editable=False,
                verbose_name="reminder notification sent at",
            ),
        )
    ]
