# Generated by Django 2.1.3 on 2019-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractzone',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='contact person'),
        ),
        migrations.AddField(
            model_name='contractzone',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contractzone',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone'),
        ),
    ]
