# Generated by Django 2.1.3 on 2019-02-28 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("areas", "0002_add_contract_zone_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractzone",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_zones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contractor",
            ),
        )
    ]
